stages:
  - build
  - test
  - register
  - deploy

build:
  stage: build
  image: docker:latest
  services:
  - docker:dind

  script:
  - docker info
  - docker build -t my-ci-test-image:2 .

teststuff:
  image: my-ci-test-image:2
  stage: test
  script:
  - py.test

testslow:
  image: my-ci-test-image:2
  stage: test
  script:
  - py.test

docker:
  stage: register
  image: canopytax/alpine
  script:
  - which python3
  when: always

production:
  stage: deploy
  script:
  - echo "hello"
  when: manual


